version: 2
before:
  hooks:
    - make docs

env:
  - HEROKU_APP_NAME={{ if index .Env "HEROKU_APP_NAME"  }}{{ .Env.HEROKU_APP_NAME }}{{ else }}default-app-name{{ end }}

builds:
  - id: pgconfigctl
    binary: pgconfigctl
    main: cmd/pgconfigctl/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s
      - -w
      - -X github.com/pgconfig/api/pkg/version.Tag={{.Version}}
      - -X github.com/pgconfig/api/pkg/version.Commit={{.Commit}}

  - id: api
    binary: api
    main: cmd/api/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s
      - -w
      - -X github.com/pgconfig/api/pkg/version.Tag={{.Version}}
      - -X github.com/pgconfig/api/pkg/version.Commit={{.Commit}}
nfpms:
  - id: default
    package_name: pgconfigctl
    file_name_template: >-
      {{ .Binary }}-
      {{ .Version }}-
      {{- if eq .Os "darwin" }}MacOS
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}-
      {{ .Arch }}

    # builds:
    #   - pgconfigctl

    homepage: https://pgconfig.org/
    maintainer: Sebastian Webber <sebastian@pgconfig.org>
    description: CLI for the pgconfig.org website

    license: MIT

    formats:
      - deb
      - rpm

archives:
  - id: pgconfigctl
    # builds:
    #   - pgconfigctl
    name_template: >-
      {{ .Binary }}-
      {{ .Version }}-
      {{- if eq .Os "darwin" }}MacOS
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}-
      {{ .Arch }}
    # format: binary # deprecated
    formats:
      - tar.gz # standard default, user likely wants binary-only but v2 deprecates raw binary output in archives?
      # If 'binary' format is desired, it's usually just copying the file.
      # If I comment out format, it defaults to tar.gz.
      # If I use formats: ["binary"] it might work if 'binary' is still a valid value inside the list.
      # Let's try formats: ["binary"] first as the user had 'format: binary'.
      - binary

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*(feat|chore)[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

dockers_v2:
  - id: pgconfigctl
    ids:
      - pgconfigctl
    dockerfile: cmd/pgconfigctl/Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64,linux/arm64"
    images:
      - "docker.io/pgconfig/pgconfigctl"
      - "ghcr.io/pgconfig/pgconfigctl"
    tags:
      - "v{{ .Version }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "v{{ .Major }}"
      - "latest"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "pgconfig-{{.ProjectName}}"
      "org.opencontainers.image.website": "pgconfig.org"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"

  - id: api
    ids:
      - api
    dockerfile: cmd/api/Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64,linux/arm64"
    extra_files:
      - rules.yml
      - pg-docs.yml
    images:
      - "docker.io/pgconfig/api"
      - "ghcr.io/pgconfig/api"
      - "registry.heroku.com/{{ .Env.HEROKU_APP_NAME }}/web"
    tags:
      - "v{{ .Version }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "v{{ .Major }}"
      - "latest"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "pgconfig-{{.ProjectName}}"
      "org.opencontainers.image.website": "pgconfig.org"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
