//! The four renderings of the v1 categories: the conf file, `ALTER SYSTEM`
//! statements, the StackGres `SGPostgresConfig`, and JSON.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use super::Category;

/// The format names `pgconfigctl --format` accepts.
pub const EXPORT_FORMATS: [&str; 9] = [
    "json",
    "conf",
    "unix",
    "alter_system",
    "sql",
    "stackgres",
    "sg",
    "sgpostgresconfig",
    "yaml",
];

/// Settings the StackGres operator manages itself and refuses in an
/// `SGPostgresConfig`.
/// <https://github.com/ongres/stackgres/blob/main/stackgres-k8s/src/operator/src/main/resources/postgresql-blocklist.properties>
const STACKGRES_BLOCKED: [&str; 19] = [
    "listen_addresses",
    "port",
    "hot_standby",
    "fsync",
    "logging_collector",
    "log_destination",
    "log_directory",
    "log_filename",
    "log_rotation_age",
    "log_rotation_size",
    "log_truncate_on_rotation",
    "wal_level",
    "track_commit_timestamp",
    "wal_log_hints",
    "archive_mode",
    "archive_command",
    "lc_messages",
    "wal_compression",
    "dynamic_library_path",
];

enum Rendering {
    Json,
    Conf,
    Sql,
    StackGres,
}

/// Renders the categories in the named format. The name is matched exactly,
/// and an unknown name renders the conf file, as REST v1 always did.
///
/// `build` is the version text of the `Generated by PGConfig` header. Each
/// entry of `extra` is one more header line, written as given: REST v1 passes
/// the request URL followed by a newline. JSON has no header.
pub fn export(
    format: &str,
    categories: &[Category],
    pg_version: f32,
    build: &str,
    extra: &[String],
) -> String {
    let rendering = match format {
        "json" => Rendering::Json,
        "alter_system" | "sql" => Rendering::Sql,
        "stackgres" | "sg" | "sgpostgresconfig" | "yaml" => Rendering::StackGres,
        _ => Rendering::Conf,
    };
    let comment = if matches!(rendering, Rendering::Sql) {
        "--"
    } else {
        "#"
    };

    let mut out = String::new();
    if matches!(rendering, Rendering::StackGres) {
        out.push_str("---\n");
    }
    if !matches!(rendering, Rendering::Json) {
        writeln!(out, "{comment} Generated by PGConfig {build}").unwrap();
        for line in extra {
            write!(out, "{comment} {line}").unwrap();
        }
        out.push('\n');
    }

    match rendering {
        Rendering::Json => out.push_str(&serde_json::to_string_pretty(categories).unwrap()),
        Rendering::Conf => conf_file(&mut out, categories),
        Rendering::Sql => alter_system(&mut out, categories),
        Rendering::StackGres => stackgres(&mut out, categories, pg_version),
    }
    out
}

fn conf_file(out: &mut String, categories: &[Category]) {
    for category in categories {
        writeln!(out, "# {}", category.description).unwrap();
        for parameter in category.parameters() {
            if let Some(comment) = parameter.comment {
                write!(out, "\n# {comment}\n").unwrap();
            }
            if parameter.format == "string" {
                writeln!(out, "{} = '{}'", parameter.name, parameter.value).unwrap();
            } else {
                writeln!(out, "{} = {}", parameter.name, parameter.value).unwrap();
            }
        }
        out.push('\n');
    }
}

fn alter_system(out: &mut String, categories: &[Category]) {
    for category in categories {
        writeln!(out, "-- {}", category.description).unwrap();
        for parameter in category.parameters() {
            if let Some(comment) = parameter.comment {
                write!(out, "\n-- {comment}\n").unwrap();
            }
            writeln!(
                out,
                "ALTER SYSTEM SET {} TO '{}';",
                parameter.name, parameter.value
            )
            .unwrap();
        }
        out.push('\n');
    }
}

fn stackgres(out: &mut String, categories: &[Category], pg_version: f32) {
    // A float rounded to no decimals, as v1 always wrote it: 9.6 becomes "10".
    let postgres_version = format!("{pg_version:.0}");
    let settings: BTreeMap<&str, &str> = categories
        .iter()
        .flat_map(Category::parameters)
        .filter(|parameter| !STACKGRES_BLOCKED.contains(&parameter.name))
        .map(|parameter| (parameter.name, parameter.value.as_str()))
        .collect();

    out.push_str("apiVersion: stackgres.io/v1\n");
    out.push_str("kind: SGPostgresConfig\n");
    out.push_str("metadata:\n");
    out.push_str("  name: pgconfig-org-generated\n");
    out.push_str("spec:\n");
    writeln!(out, "  postgresVersion: {}", yaml_scalar(&postgres_version)).unwrap();
    if settings.is_empty() {
        out.push_str("  postgresql.conf: {}\n");
        return;
    }
    out.push_str("  postgresql.conf:\n");
    for (name, value) in settings {
        writeln!(out, "    {name}: {}", yaml_scalar(value)).unwrap();
    }
}

/// Writes a string the way Go's yaml.v2 did. A text that YAML would read as
/// another type is double-quoted, a text that cannot be written plain is
/// single-quoted, and the rest is plain. This covers the values pgconfig
/// produces, not every YAML string.
fn yaml_scalar(text: &str) -> String {
    if reads_as_another_type(text) {
        return format!("\"{}\"", text.replace('\\', "\\\\").replace('"', "\\\""));
    }
    let indicator = text.starts_with([
        '#', ',', '[', ']', '{', '}', '&', '*', '!', '|', '>', '\'', '"', '%', '@', '`', '-', '?',
        ':',
    ]);
    let padded = text.starts_with(' ') || text.ends_with(' ');
    if indicator || padded || text.contains(": ") || text.contains(" #") {
        return format!("'{}'", text.replace('\'', "''"));
    }
    text.to_string()
}

/// Whether YAML 1.1 resolves the plain scalar to a null, a boolean, or a
/// number.
fn reads_as_another_type(text: &str) -> bool {
    const WORDS: [&str; 11] = [
        "", "~", "null", "y", "n", "yes", "no", "on", "off", "true", "false",
    ];
    if WORDS.contains(&text.to_ascii_lowercase().as_str()) {
        return true;
    }
    let unsigned = text.strip_prefix(['+', '-']).unwrap_or(text);
    let mut parts = unsigned.splitn(2, ['e', 'E']);
    let mantissa = parts.next().unwrap_or_default();
    let exponent = parts.next();
    let digits = |part: &str| !part.is_empty() && part.bytes().all(|b| b.is_ascii_digit());
    let mantissa_is_number = match mantissa.split_once('.') {
        Some((whole, fraction)) => {
            (digits(whole) && (fraction.is_empty() || digits(fraction)))
                || (whole.is_empty() && digits(fraction))
        }
        None => digits(mantissa),
    };
    let exponent_is_number = exponent
        .is_none_or(|exponent| digits(exponent.strip_prefix(['+', '-']).unwrap_or(exponent)));
    mantissa_is_number && exponent_is_number
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn yaml_quotes_what_would_read_as_a_number_or_a_boolean() {
        for (text, written) in [
            ("100", "\"100\""),
            ("-1", "\"-1\""),
            ("0.9", "\"0.9\""),
            ("on", "\"on\""),
            ("", "\"\""),
            ("4GB", "4GB"),
            ("10s", "10s"),
            ("worker", "worker"),
            ("LOCAL0", "LOCAL0"),
        ] {
            assert_eq!(yaml_scalar(text), written, "{text:?}");
        }
    }

    #[test]
    fn yaml_single_quotes_what_cannot_be_plain() {
        assert_eq!(
            yaml_scalar("%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h "),
            "'%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '"
        );
        assert_eq!(
            yaml_scalar("user=%u,db=%d,app=%a,client=%h "),
            "'user=%u,db=%d,app=%a,client=%h '"
        );
    }
}
