//! Turns `rules.yml`, `pg-docs.yml`, and the files of `parameters/` into Rust
//! tables, so the crate carries its data and needs no YAML parser at run
//! time.

use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use yaml_rust2::parser::{Event, EventReceiver, Parser};
use yaml_rust2::scanner::TScalarStyle;

/// A YAML document where every scalar keeps its source text. A typed loader
/// would turn `default_value: 010` into the number 10.
enum Node {
    Scalar(String),
    Sequence(Vec<Node>),
    Mapping(Vec<(String, Node)>),
}

impl Node {
    fn text(&self) -> &str {
        match self {
            Node::Scalar(text) => text,
            _ => "",
        }
    }

    fn entries(&self) -> &[(String, Node)] {
        match self {
            Node::Mapping(entries) => entries,
            _ => &[],
        }
    }

    fn items(&self) -> &[Node] {
        match self {
            Node::Sequence(items) => items,
            _ => &[],
        }
    }

    fn get(&self, key: &str) -> Option<&Node> {
        self.entries()
            .iter()
            .find(|(name, _)| name == key)
            .map(|(_, node)| node)
    }

    fn text_of(&self, key: &str) -> &str {
        self.get(key).map_or("", Node::text)
    }
}

#[derive(Default)]
struct Builder {
    /// Open containers, innermost last. A mapping also holds the key that is
    /// waiting for its value.
    stack: Vec<(Node, Option<String>)>,
    root: Option<Node>,
}

impl Builder {
    fn push(&mut self, node: Node) {
        match self.stack.last_mut() {
            None => self.root = Some(node),
            Some((Node::Sequence(items), _)) => items.push(node),
            Some((Node::Mapping(entries), key)) => match key.take() {
                Some(key) => entries.push((key, node)),
                None => *key = Some(node.text().to_string()),
            },
            Some((Node::Scalar(_), _)) => unreachable!("a scalar holds no children"),
        }
    }
}

impl EventReceiver for Builder {
    fn on_event(&mut self, event: Event) {
        match event {
            Event::Scalar(text, style, _, _) => {
                // An unquoted `~` or `null` is the YAML null, which the Go
                // loader read into an empty string.
                let null = style == TScalarStyle::Plain && matches!(text.as_str(), "~" | "null");
                self.push(Node::Scalar(if null { String::new() } else { text }));
            }
            Event::SequenceStart(..) => self.stack.push((Node::Sequence(Vec::new()), None)),
            Event::MappingStart(..) => self.stack.push((Node::Mapping(Vec::new()), None)),
            Event::SequenceEnd | Event::MappingEnd => {
                let (node, _) = self.stack.pop().expect("an open container");
                self.push(node);
            }
            Event::Alias(_) => panic!("YAML aliases are not supported in the data files"),
            _ => {}
        }
    }
}

fn load(path: &Path) -> Node {
    println!("cargo::rerun-if-changed={}", path.display());
    let source = fs::read_to_string(path)
        .unwrap_or_else(|err| panic!("cannot read {}: {err}", path.display()));
    parse(&source, path)
}

fn parse(source: &str, path: &Path) -> Node {
    let mut builder = Builder::default();
    Parser::new_from_str(source)
        .load(&mut builder, false)
        .unwrap_or_else(|err| panic!("cannot parse {}: {err}", path.display()));
    builder
        .root
        .unwrap_or_else(|| panic!("{} is empty", path.display()))
}

/// The table of `parameters/`: per major version, oldest first, its files
/// sorted by name. The text stays in the files, included as they are.
fn parameter_docs(dir: &Path) -> String {
    println!("cargo::rerun-if-changed={}", dir.display());
    let list = |dir: &Path| -> Vec<std::path::PathBuf> {
        let mut paths: Vec<_> = fs::read_dir(dir)
            .unwrap_or_else(|err| panic!("cannot read {}: {err}", dir.display()))
            .map(|entry| entry.expect("a directory entry").path())
            .collect();
        paths.sort();
        paths
    };
    let mut versions: Vec<(Vec<u32>, std::path::PathBuf)> = list(dir)
        .into_iter()
        .filter(|path| path.is_dir())
        .map(|path| {
            let name = path.file_name().unwrap().to_string_lossy().into_owned();
            let numbers = name
                .split('.')
                .map(|number| {
                    number
                        .parse()
                        .unwrap_or_else(|_| panic!("{name} is not a version"))
                })
                .collect();
            (numbers, path)
        })
        .collect();
    versions.sort();

    let mut out = String::from(
        "// Generated by build.rs from parameters/.\n\npub(crate) static PARAMETER_DOCS: &[(&str, &[ParameterDoc])] = &[\n",
    );
    for (_, version_dir) in versions {
        let version = version_dir
            .file_name()
            .unwrap()
            .to_string_lossy()
            .into_owned();
        writeln!(out, "    ({version:?}, &[").unwrap();
        for path in list(&version_dir) {
            if path.extension().is_none_or(|extension| extension != "md") {
                continue;
            }
            let source = fs::read_to_string(&path)
                .unwrap_or_else(|err| panic!("cannot read {}: {err}", path.display()));
            let (front_matter, text) = source
                .strip_prefix("---\n")
                .and_then(|rest| rest.split_once("\n---\n"))
                .unwrap_or_else(|| panic!("{} has no front matter", path.display()));
            // The text starts after the closing `---` and the blank line.
            let text_start = source.len() - text.trim_start_matches('\n').len();
            let fields = parse(front_matter, &path);
            let text = |key: &str| fields.get(key).map(Node::text);
            let required =
                |key: &str| text(key).unwrap_or_else(|| panic!("{} has no {key}", path.display()));
            let values: Vec<&str> = fields
                .get("values")
                .map(Node::items)
                .unwrap_or_default()
                .iter()
                .map(Node::text)
                .collect();
            writeln!(
                out,
                "        ParameterDoc {{ name: {:?}, param_type: {:?}, category: {:?}, short_desc: {:?}, extra_desc: {:?}, context: {:?}, unit: {:?}, default: {:?}, min: {:?}, max: {:?}, values: &{values:?}, url: {:?}, markdown: include_str!({:?}), text_start: {text_start} }},",
                required("name"),
                text("type"),
                text("category"),
                text("short_desc"),
                text("extra_desc"),
                text("context"),
                text("unit"),
                text("default"),
                text("min"),
                text("max"),
                required("url"),
                path,
            )
            .unwrap();
        }
        out.push_str("    ]),\n");
    }
    out.push_str("];\n");
    out
}

fn main() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let rules = load(&root.join("rules.yml"));
    let docs = load(&root.join("pg-docs.yml"));

    let mut out = String::from("// Generated by build.rs from rules.yml and pg-docs.yml.\n\n");

    out.push_str("pub(crate) static RULES: &[(&str, &[(&str, RuleDoc)])] = &[\n");
    for (category, parameters) in rules.get("categories").expect("categories").entries() {
        writeln!(out, "    ({category:?}, &[").unwrap();
        for (name, rule) in parameters.entries() {
            // Go serialized this map with its keys sorted.
            let links: BTreeMap<&str, &str> = rule
                .get("recomendations")
                .map(Node::entries)
                .unwrap_or_default()
                .iter()
                .map(|(title, url)| (title.as_str(), url.text()))
                .collect();
            writeln!(
                out,
                "        ({name:?}, RuleDoc {{ abstract_text: {:?}, recomendations: &{:?} }}),",
                rule.text_of("abstract"),
                links.into_iter().collect::<Vec<_>>(),
            )
            .unwrap();
        }
        out.push_str("    ]),\n");
    }
    out.push_str("];\n\n");

    out.push_str("pub(crate) static PG_DOCS: &[(&str, &[(&str, ParamDoc)])] = &[\n");
    for (version, parameters) in docs.get("documentation").expect("documentation").entries() {
        writeln!(out, "    ({version:?}, &[").unwrap();
        for (name, doc) in parameters.entries() {
            let details: Vec<&str> = doc
                .get("details")
                .map(Node::items)
                .unwrap_or_default()
                .iter()
                .map(Node::text)
                .collect();
            writeln!(
                out,
                "        ({name:?}, ParamDoc {{ title: {:?}, short_desc: {:?}, details: &{details:?}, url: {:?}, conf_url: {:?}, recomendations_conf: {:?}, param_type: {:?}, default_value: {:?}, min_value: {:?}, max_value: {:?} }}),",
                doc.text_of("title"),
                doc.text_of("short_desc"),
                doc.text_of("url"),
                doc.text_of("conf_url"),
                doc.text_of("recomendations_conf"),
                doc.text_of("type"),
                doc.text_of("default_value"),
                doc.text_of("min_value"),
                doc.text_of("max_value"),
            )
            .unwrap();
        }
        out.push_str("    ]),\n");
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out_dir).join("data.rs"), out).expect("write the generated data");
    fs::write(
        Path::new(&out_dir).join("parameter_docs.rs"),
        parameter_docs(&root.join("parameters")),
    )
    .expect("write the generated parameter documentation");
}
