package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"

	"github.com/charmbracelet/log"

	_ "github.com/pgconfig/api/cmd/api/docs" // docs is generated by Swag CLI, you have to import it.
	v1 "github.com/pgconfig/api/cmd/api/handlers/v1"
	"github.com/pgconfig/api/cmd/api/routes"
	"github.com/pgconfig/api/pkg/version"
)

var (
	port      int
	rulesFile string
	docsFile  string
)

func getDefaultPort(envName string) int {
	defaultPort := 3000
	val := os.Getenv(envName)

	out, err := strconv.Atoi(val)
	if err != nil {
		return defaultPort
	}

	return out
}

func setupArgs() {
	flag.IntVar(&port, "port", getDefaultPort("PORT"), "Listen port")
	flag.StringVar(&rulesFile, "rules-file", "./rules.yml", "Rules file")
	flag.StringVar(&docsFile, "docs-file", "./pg-docs.yml", "Rules file")
	flag.Parse()
}

func main() {
	setupArgs()

	if err := v1.LoadConfig(rulesFile, docsFile); err != nil {
		log.Fatal("could not load configuration", "err", err)
	}

	log.Info("PGConfig API", "ver", version.Pretty())

	app := routes.New()
	if err := app.Listen(fmt.Sprintf(":%d", port)); err != nil {
		log.Errorf("not running API: %v", err)
	}
}
