package main

import (
	"flag"
	"fmt"
	"log"

	_ "github.com/pgconfig/api/cmd/api/docs" // docs is generated by Swag CLI, you have to import it.
	v1 "github.com/pgconfig/api/cmd/api/handlers/v1"

	"github.com/pgconfig/api/cmd/api/routes"
	"github.com/pgconfig/api/pkg/version"
)

var (
	port      int
	rulesFile string
	docsFile  string
)

func init() {
	flag.IntVar(&port, "port", 3000, "Listen port")
	flag.StringVar(&rulesFile, "rules-file", "./rules.yml", "Rules file")
	flag.StringVar(&docsFile, "docs-file", "./pg-docs.yml", "Rules file")
	flag.Parse()

	v1.Prepare(rulesFile, docsFile)
}

func main() {
	log.Printf("%s (%s)\n", version.Tag, version.Commit)

	app := routes.New()
	if err := app.Listen(fmt.Sprintf(":%d", port)); err != nil {
		log.Println("[ERR] not running API: ", err)
	}
}
