package main

import (
	"flag"
	"log"

	_ "github.com/pgconfig/api/cmd/api/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/pgconfig/api/cmd/api/routes"
	"github.com/pgconfig/api/pkg/version"
)

var port int

func init() {
	flag.IntVar(&port, "version", 3000, "Listen port")
	flag.Parse()
}

func main() {
	log.Printf("%s (%s)\n", version.Tag, version.Commit)

	app := routes.New()
	if err := app.Listen(":3000"); err != nil {
		log.Println("[ERR] not running API: ", err)
	}
}
