import assert from "node:assert/strict";
import { test } from "node:test";
import { apiUrl, apiVersionLabel, decodeBody, getTuning } from "../src/lib/api.ts";

test("a JSON body gives its data and the API version that produced it", () => {
  const body = JSON.stringify({
    data: [{ environment: "WEB", configuration: [] }],
    meta: { version: "3.6.1 (abc123)" },
  });
  assert.deepStrictEqual(decodeBody(body), {
    output: [{ environment: "WEB", configuration: [] }],
    version: "3.6.1 (abc123)",
  });
});

test("a rendered configuration file is returned as the text it is", () => {
  const body = "# Generated by PGConfig\nshared_buffers = 1GB\n";
  assert.deepStrictEqual(decodeBody(body), { output: body, version: null });
});

test("a JSON body without a version reports none", () => {
  assert.deepStrictEqual(decodeBody('{"data":["WEB"]}'), { output: ["WEB"], version: null });
});

test("the version label drops the build suffix", () => {
  assert.strictEqual(apiVersionLabel("3.6.1 (abc123)"), "api (3.6.1)");
  assert.strictEqual(apiVersionLabel("development (latest)"), "api (development)");
});

test("an unknown version has no label", () => {
  assert.strictEqual(apiVersionLabel(null), null);
  assert.strictEqual(apiVersionLabel(""), null);
});

test("requests go to the same origin unless a base URL is configured", () => {
  assert.strictEqual(
    apiUrl(undefined, "get-config", "format=conf&cpus=2"),
    "/v1/tuning/get-config?format=conf&cpus=2",
  );
  assert.strictEqual(
    apiUrl("https://api.pgconfig.org/v1/tuning", "get-config", "cpus=2"),
    "https://api.pgconfig.org/v1/tuning/get-config?cpus=2",
  );
  assert.strictEqual(
    apiUrl("https://api.pgconfig.org/v1/tuning/", "get-config", "cpus=2"),
    "https://api.pgconfig.org/v1/tuning/get-config?cpus=2",
  );
});

test("a successful request resolves with the decoded body", async () => {
  const requested = [];
  const fetcher = async (url) => {
    requested.push(url);
    return new Response('{"data":["WEB"],"meta":{"version":"3.6.1"}}', { status: 200 });
  };
  const result = await getTuning("list-environments", "", { fetcher });
  assert.deepStrictEqual(result, { output: ["WEB"], version: "3.6.1" });
  assert.deepStrictEqual(requested, ["/v1/tuning/list-environments?"]);
});

test("a rejected request fails with the status and the API's own message", async () => {
  const fetcher = async () =>
    new Response('{"errors":{"code":500,"message":"could not parse pg version"}}', {
      status: 500,
    });
  await assert.rejects(
    getTuning("get-config", "pg_version=abc", { fetcher }),
    /Request failed with status code 500: could not parse pg version/,
  );
});

test("a rejected request without a readable message still reports its status", async () => {
  const fetcher = async () => new Response("<html>Bad gateway</html>", { status: 502 });
  await assert.rejects(
    getTuning("get-config", "", { fetcher }),
    /Request failed with status code 502$/,
  );
});
