//! Replaces the build version in an output with a placeholder. The version is
//! the only part of an output that differs between two builds of the same
//! rules, so it is the only part the goldens do not pin.

use serde_json::Value;

const GENERATED_BY: [&str; 2] = ["# Generated by PGConfig ", "-- Generated by PGConfig "];
const CLI_VERSION: &str = "pgconfigctl - ";

/// Normalizes a text output: the `Generated by PGConfig <version>` header of
/// the conf, SQL, and StackGres formats, and the line `pgconfigctl version`
/// prints.
pub fn text(output: &str) -> String {
    let mut out = String::with_capacity(output.len());
    for (index, line) in output.split_inclusive('\n').enumerate() {
        let (content, newline) = match line.strip_suffix('\n') {
            Some(content) => (content, "\n"),
            None => (line, ""),
        };
        // The header is the first line, or the second after a YAML `---`.
        let prefix = (index < 2)
            .then(|| {
                GENERATED_BY
                    .iter()
                    .find(|prefix| content.starts_with(**prefix))
            })
            .flatten()
            .or_else(|| (index == 0 && content.starts_with(CLI_VERSION)).then_some(&CLI_VERSION));
        match prefix {
            Some(prefix) => {
                out.push_str(prefix);
                out.push_str("<version>");
            }
            None => out.push_str(content),
        }
        out.push_str(newline);
    }
    out
}

/// Normalizes a REST v1 JSON body: `meta.version`, and the three fields of
/// the `/v1/version` payload.
pub fn rest_json(path: &str, body: &mut Value) {
    if let Some(version) = body.pointer_mut("/meta/version")
        && version.is_string()
    {
        *version = Value::from("<version>");
    }
    if is_version_route(path) {
        for (field, placeholder) in [
            ("version", "<tag>"),
            ("build", "<commit>"),
            ("pretty", "<version>"),
        ] {
            if let Some(value) = body.pointer_mut(&format!("/data/{field}"))
                && value.is_string()
            {
                *value = Value::from(placeholder);
            }
        }
    }
}

fn is_version_route(path: &str) -> bool {
    let route = path.split('?').next().unwrap_or(path);
    route
        .trim_end_matches('/')
        .eq_ignore_ascii_case("/v1/version")
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn conf_header_loses_its_version() {
        let output =
            "# Generated by PGConfig development (latest)\n# http://host/path\n\nwork_mem = 5MB\n";

        assert_eq!(
            text(output),
            "# Generated by PGConfig <version>\n# http://host/path\n\nwork_mem = 5MB\n"
        );
    }

    #[test]
    fn sql_header_loses_its_version() {
        assert_eq!(
            text("-- Generated by PGConfig 3.6.1 (abc)\n\n-- Memory\n"),
            "-- Generated by PGConfig <version>\n\n-- Memory\n"
        );
    }

    #[test]
    fn stackgres_header_comes_after_the_document_marker() {
        assert_eq!(
            text("---\n# Generated by PGConfig 3.6.1 (abc)\n\napiVersion: stackgres.io/v1\n"),
            "---\n# Generated by PGConfig <version>\n\napiVersion: stackgres.io/v1\n"
        );
    }

    #[test]
    fn cli_version_line_loses_its_version() {
        assert_eq!(
            text("pgconfigctl - 3.6.1 (abc)\n"),
            "pgconfigctl - <version>\n"
        );
    }

    #[test]
    fn a_parameter_value_that_looks_like_a_header_is_kept() {
        let output = "# Generated by PGConfig x\n\n# Memory\n# Generated by PGConfig y\n";

        assert_eq!(
            text(output),
            "# Generated by PGConfig <version>\n\n# Memory\n# Generated by PGConfig y\n"
        );
    }

    #[test]
    fn meta_version_is_replaced_in_every_response() {
        let mut body = json!({"data": ["WEB"], "meta": {"version": "development (latest)"}});

        rest_json("/v1/tuning/list-environments", &mut body);

        assert_eq!(
            body,
            json!({"data": ["WEB"], "meta": {"version": "<version>"}})
        );
    }

    #[test]
    fn version_route_payload_is_replaced() {
        let mut body = json!({
            "data": {"version": "3.6.1", "build": "abc", "pretty": "3.6.1 (abc)"},
            "meta": {"version": "3.6.1 (abc)"}
        });

        rest_json("/V1/Version/?x=1", &mut body);

        assert_eq!(
            body,
            json!({
                "data": {"version": "<tag>", "build": "<commit>", "pretty": "<version>"},
                "meta": {"version": "<version>"}
            })
        );
    }

    #[test]
    fn an_error_body_is_left_alone() {
        let mut body = json!({"errors": {"code": 500, "message": "Invalid OS"}});
        let expected = body.clone();

        rest_json("/v1/tuning/get-config?os_type=bsd", &mut body);

        assert_eq!(body, expected);
    }
}
